// Load the letter weights generated by our Python script
fetch('data/letter_weights.json')
  .then(response => response.json())
  .then(data => {
    // Sort letters by weight, highest first
    const sorted = Object.entries(data).sort((a, b) => b[1] - a[1]);
    const labels = sorted.map(entry => entry[0]);
    const values = sorted.map(entry => entry[1]);

    // Draw the bar chart with Catppuccin Mocha colours
    const ctx = document.getElementById('letterChart').getContext('2d');
    new Chart(ctx, {
      type: 'bar',
      data: {
        labels: labels,
        datasets: [{
          label: 'Letter frequency (%)',
          data: values,
          backgroundColor: labels.map((_, i) =>
            i < 5 ? 'rgba(203,166,247,0.7)' :   // top 5 in mauve
            i < 10 ? 'rgba(137,180,250,0.7)' :  // next 5 in blue
            'rgba(148,226,213,0.4)'              // rest in teal
          ),
          borderColor: 'rgba(180,190,254,0.3)',
          borderWidth: 1,
          borderRadius: 6
        }]
      },
      options: {
        responsive: true,
        plugins: {
          legend: { labels: { color: '#cdd6f4' } }
        },
        scales: {
          x: {
            ticks: { color: '#cdd6f4' },
            grid: { color: 'rgba(69,71,90,0.5)' }
          },
          y: {
            ticks: { color: '#cdd6f4' },
            grid: { color: 'rgba(69,71,90,0.5)' },
            title: {
              display: true,
              text: 'Frequency (%)',
              color: '#a6adc8'
            }
          }
        }
      }
    });
  });