// Load the letter weights generated by our Python script
fetch('data/letter_weights.json')
  .then(response => response.json())
  .then(data => {
    // Sort letters by weight, highest first
    const sorted = Object.entries(data).sort((a, b) => b[1] - a[1]);
    const labels = sorted.map(entry => entry[0]);
    const values = sorted.map(entry => entry[1]);

    // Draw the bar chart
    const ctx = document.getElementById('letterChart').getContext('2d');
    new Chart(ctx, {
      type: 'bar',
      data: {
        labels: labels,
        datasets: [{
          label: 'Letter frequency (%)',
          data: values,
          backgroundColor: 'rgba(180, 190, 254, 0.5)',
          borderColor: 'rgba(180, 190, 254, 1)',
          borderWidth: 1
        }]
      },
      options: {
        plugins: {
          legend: { labels: { color: '#cdd6f4' } }
        },
        scales: {
          x: { ticks: { color: '#cdd6f4' }, grid: { color: '#313244' } },
          y: { ticks: { color: '#cdd6f4' }, grid: { color: '#313244' } }
        }
      }
    });
  });