// ── Audio ─────────────────────────────────────────────────────
// This creates an audio object pointing to our music file
const timerMusic = new Audio('timer-music.mp3');

// Track how many vowels and consonants have been picked
let vowelCount = 0;
let consonantCount = 0;

// ── Letter weights ────────────────────────────────────────────
// Loaded from the JSON file generated by our Python script
let letterWeights = {};

fetch('data/letter_weights.json')
  .then(response => response.json())
  .then(data => {
    letterWeights = data;
    console.log('Letter weights loaded');
  });

// ── Letter pools ──────────────────────────────────────────────
// These are the two sets of letters the player can pick from.
const VOWELS = ['A', 'E', 'I', 'O', 'U'];
const CONSONANTS = ['B', 'C', 'D', 'F', 'G', 'H', 'J', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'X', 'Y', 'Z'];

// ── Game state ────────────────────────────────────────────────
// This array will store the letters the player has chosen so far.
// We start with an empty array and add to it as they click.
let selectedLetters = [];

// ── Check letter repeat limit ─────────────────────────────────
// Returns true if the letter has already appeared 2 times
function isAtRepeatLimit(letter) {
  const count = selectedLetters.filter(l => l === letter).length;
  return count >= 2;
}

// ── Weighted letter picker ────────────────────────────────────
// Instead of picking randomly from a plain array, we use the
// weights to make common letters appear more often.
function pickLetter(pool) {
  // Get total weight for letters in this pool (vowels or consonants)
  let totalWeight = pool.reduce((sum, letter) => {
    return sum + (letterWeights[letter] || 1);
  }, 0);

  // Pick a random point along the total weight
  let random = Math.random() * totalWeight;

  // Walk through the pool until we hit that point
  for (let letter of pool) {
    random -= (letterWeights[letter] || 1);
    if (random <= 0) return letter;
  }

  // Fallback just in case
  return pool[pool.length - 1];
}

// ── Add a letter to the board ─────────────────────────────────
// This function adds a letter tile to the page and records it.
function addLetter(letter) {
  // Stop if the player already has 9 letters
  if (selectedLetters.length >= 9) return;

  // Save the letter in our array
  selectedLetters.push(letter);

  // Find the board element in the HTML
  const board = document.getElementById('letter-board');

  // Create a new <div> element to act as the tile
  const tile = document.createElement('div');
  tile.classList.add('tile');   // add a CSS class so we can style it
  tile.textContent = letter;    // set the text inside the tile

  // Add the tile to the board on the page
  board.appendChild(tile);
}

// ── Button event listeners (with Countdown rules) ─────────────
// Real Countdown rules: max 5 vowels, max 6 consonants, 9 total
document.getElementById('vowel-btn').addEventListener('click', function() {
  if (selectedLetters.length >= 9) return;
  if (vowelCount >= 5) return;

  let letter = pickLetter(VOWELS);

  // Keep picking until we find one that isn't at its repeat limit
  let attempts = 0;
  while (isAtRepeatLimit(letter) && attempts < 20) {
    letter = pickLetter(VOWELS);
    attempts++;
  }

  addLetter(letter);
  vowelCount++;

  if (vowelCount >= 5) document.getElementById('vowel-btn').disabled = true;
  if (selectedLetters.length >= 9) document.getElementById('consonant-btn').disabled = true;
});

document.getElementById('consonant-btn').addEventListener('click', function() {
  if (selectedLetters.length >= 9) return;
  if (vowelCount >= 5) return;

  let letter = pickLetter(VOWELS);

  // Keep picking until we find one that isn't at its repeat limit
  let attempts = 0;
  while (isAtRepeatLimit(letter) && attempts < 20) {
    letter = pickLetter(VOWELS);
    attempts++;
  }

  addLetter(letter);
  vowelCount++;

  if (vowelCount >= 5) document.getElementById('vowel-btn').disabled = true;
  if (selectedLetters.length >= 9) document.getElementById('consonant-btn').disabled = true;
});

// ── Timer ─────────────────────────────────────────────────────
// We store the interval ID so we can stop it later
let timerInterval = null;

// This function starts the 30 second countdown
function startTimer() {
  // Don't start a second timer if one is already running
  if (timerInterval !== null) return;
  // Play the music when the timer starts
  timerMusic.play();
  let timeLeft = 30;

  // setInterval runs a function repeatedly, every 1000ms (1 second)
  timerInterval = setInterval(function() {
    timeLeft--;

    // Update the number shown on the page
    document.getElementById('timer').textContent = timeLeft;

    // When it hits 0, stop the timer
    if (timeLeft <= 0) {
      clearInterval(timerInterval);
      timerInterval = null;
      // Stop the music when the timer ends
      timerMusic.pause();
      timerMusic.currentTime = 0; // rewind to the start for next round 

      // Disable the letter buttons so no more letters can be added
      document.getElementById('vowel-btn').disabled = true;
      document.getElementById('consonant-btn').disabled = true;
    }
  }, 1000);
}

// Listen for the Start Timer button
document.getElementById('start-btn').addEventListener('click', startTimer);

// ── Dictionary ────────────────────────────────────────────────
// We'll store all valid words in a Set (like an array but much
// faster for checking if a word exists)
let dictionary = new Set();

// Fetch the word list file and load it into the Set
// fetch() loads a file asynchronously (in the background)
fetch('data/words_filtered.txt')
  .then(response => response.text())   // read the file as text
  .then(text => {
    // Split the text into individual words (one per line)
    // and add each one to our Set
    text.split('\n').forEach(word => {
      dictionary.add(word.trim().toLowerCase());
    });
    console.log('Dictionary loaded:', dictionary.size, 'words');
  });

// ── Word validation ───────────────────────────────────────────
// Check if the player's word only uses available letters
function isValidLetterUse(word, letters) {
  // Make a copy of the letters array so we can remove letters as we use them
  let available = [...letters];

  for (let char of word.toUpperCase()) {
    let index = available.indexOf(char);
    // If the letter isn't available, the word is invalid
    if (index === -1) return false;
    // Remove the used letter so it can't be used twice
    available.splice(index, 1);
  }
  return true;
}

// ── Submit button ─────────────────────────────────────────────
document.getElementById('submit-btn').addEventListener('click', function() {
  const word = document.getElementById('player-word').value.trim().toLowerCase();

  if (word === '') return;

  const inDictionary = dictionary.has(word);
  const usesValidLetters = isValidLetterUse(word, selectedLetters);

  if (inDictionary && usesValidLetters) {
  updateScore(word);
  showFeedback(word.toUpperCase() + ' — ' + word.length + ' letters, +' + getPoints(word) + ' pts', true);
  document.getElementById('player-word').value = '';
} else if (!usesValidLetters) {
  showFeedback('letters not on the board', false);
} else {
  showFeedback('not a valid word', false);
}
});
// ── Best Words Solver ─────────────────────────────────────────
// Check if a word can be formed from the available letters
function canFormWord(word, letters) {
  let available = [...letters];
  for (let char of word.toUpperCase()) {
    let index = available.indexOf(char);
    if (index === -1) return false;
    available.splice(index, 1);
  }
  return true;
}

// Find the best possible words from the selected letters
function findBestWords() {
  let validWords = [];

  // Go through every word in the dictionary
  dictionary.forEach(word => {
    // Only consider words up to 9 letters
    if (word.length >= 2 && word.length <= 9) {
      if (canFormWord(word, selectedLetters)) {
        validWords.push(word);
      }
    }
  });

  // Sort by length, longest first
  validWords.sort((a, b) => b.length - a.length);

  // Return the top 5
  return validWords.slice(0, 5);
}

// ── Best Words button ─────────────────────────────────────────
document.getElementById('best-words-btn').addEventListener('click', function() {
  const best = findBestWords();
  const display = document.getElementById('best-words-list');

  if (best.length === 0) {
    display.textContent = 'No words found!';
  } else {
    display.textContent = best.join(', ');
  }
});

// ── Pause / Resume Timer ──────────────────────────────────────
let isPaused = false;

document.getElementById('pause-btn').addEventListener('click', function() {
  if (isPaused) {
    // Resume — restart the interval
    isPaused = false;
    this.textContent = 'Pause';
    startTimer();
    timerMusic.play();
  } else {
    // Pause — stop the interval without resetting
    isPaused = true;
    this.textContent = 'Resume';
    clearInterval(timerInterval);
    timerInterval = null;
    timerMusic.pause();
  }
});

// ── Mute / Unmute Music ───────────────────────────────────────
let isMuted = false;

document.getElementById('mute-btn').addEventListener('click', function() {
  isMuted = !isMuted;
  timerMusic.muted = isMuted;
  this.textContent = isMuted ? 'Unmute' : 'Mute';
});

// ── Reset Game ────────────────────────────────────────────────
// Clears the board and resets everything back to the start state
document.getElementById('reset-btn').addEventListener('click', function() {
  // Clear the letters array
  selectedLetters = [];
  vowelCount = 0;
  consonantCount = 0;

  // Clear the tiles from the board
  document.getElementById('letter-board').innerHTML = '';

  // Reset the timer display
  document.getElementById('timer').textContent = '30';

  // Stop and reset the timer interval
  clearInterval(timerInterval);
  timerInterval = null;
  isPaused = false;

  // Reset pause button text
  document.getElementById('pause-btn').textContent = 'Pause';

  // Stop the music
  timerMusic.pause();
  timerMusic.currentTime = 0;

  // Re-enable the vowel and consonant buttons
  document.getElementById('vowel-btn').disabled = false;
  document.getElementById('consonant-btn').disabled = false;

  // Clear the word input and best words
  document.getElementById('player-word').value = '';
  document.getElementById('best-words-list').textContent = '';
});

// ── Scoring ───────────────────────────────────────────────────
// Points are awarded based on word length
// 2-3 letters = 1pt, 4-5 = 2pts, 6-7 = 4pts, 8 = 7pts, 9 = 10pts
let score = 0;

function getPoints(word) {
  const len = word.length;
  if (len <= 3) return 1;
  if (len <= 5) return 2;
  if (len <= 7) return 4;
  if (len === 8) return 7;
  return 10; // 9 letters
}

function updateScore(word) {
  const points = getPoints(word);
  score += points;
  document.getElementById('score-display').textContent = `Score: ${score} (+${points})`;
}